import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#002021",
        "on-secondary-fixed-variant": "#004f53",
        "secondary-fixed": "#84f4fa",
        "secondary-container": "#84f4fa",
        "on-secondary-container": "#007074",
        "surface-container-high": "#dce9ff",
        "inverse-on-surface": "#eaf1ff",
        background: "#f8f9ff",
        primary: "#002743",
        "on-primary-fixed": "#001d34",
        "error-container": "#ffdad6",
        "on-tertiary-container": "#ff7f62",
        "on-secondary": "#ffffff",
        "primary-container": "#0b3d62",
        "secondary-fixed-dim": "#66d7dd",
        "on-surface": "#0b1c30",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#ffb4a3",
        "primary-fixed-dim": "#a2caf7",
        tertiary: "#4e0a00",
        "surface-dim": "#cbdbf5",
        "surface-container": "#e5eeff",
        "inverse-primary": "#a2caf7",
        "on-primary-container": "#80a8d3",
        error: "#ba1a1a",
        "on-primary": "#ffffff",
        "on-surface-variant": "#42474e",
        "on-primary-fixed-variant": "#1d496f",
        "surface-tint": "#386188",
        secondary: "#00696d",
        "on-tertiary-fixed-variant": "#8c1900",
        surface: "#f8f9ff",
        "on-error-container": "#93000a",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#d3e4fe",
        "surface-bright": "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        "primary-fixed": "#cfe5ff",
        "on-error": "#ffffff",
        "surface-container-low": "#eff4ff",
        "tertiary-fixed": "#ffdad2",
        "outline-variant": "#c2c7cf",
        "inverse-surface": "#213145",
        outline: "#72777f",
        "tertiary-container": "#751300",
        "on-tertiary-fixed": "#3d0600",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        "space-xl": "2rem",
        "margin-mobile": "1rem",
        "margin-desktop": "3rem",
        "space-md": "1rem",
        "space-sm": "0.75rem",
        "space-lg": "1.5rem",
        "space-2xl": "3rem",
        "margin-tablet": "2rem",
        "gutter-desktop": "1.5rem",
        "space-xs": "0.5rem",
        "gutter-mobile": "1rem",
        "space-2xs": "0.25rem",
      },
      fontFamily: {
        "headline-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-inter)", "Inter", "sans-serif"],
        "data-metric": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-lg-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "label-md": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "label-sm": ["var(--font-jetbrains-mono)", "JetBrains Mono", "monospace"],
        "display-mobile": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-sm": ["var(--font-inter)", "Inter", "sans-serif"],
      },
      fontSize: {
        "headline-lg": ["28px", { lineHeight: "36px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        display: ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "data-metric": ["22px", { lineHeight: "28px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", letterSpacing: "-0.005em", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.04em", fontWeight: "500" }],
        "label-sm": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "500" }],
        "display-mobile": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-sm": ["18px", { lineHeight: "26px", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};

export default config;
